### ISSUE TITLE
multiple input fields open automatically

### ISSUE THREAD

**Issue by 1991chandanKumar** [catalyst/moodle-filter_forumembed#1] opened 2023-05-26 19:34 UTC
I have embedded forum discussion on Quiz questions through General feedback field in Quiz question. 
After a student clicks "Submit all and finish", review page appears. When Student clicks on reply button, multiple input field automatically open up. 
[](url)

https://github.com/catalyst/moodle-filter_forumembed/assets/134736395/2931266f-433b-473c-b806-453dd4e3ae3a

**Comment by danmarsden** [comment] 2023-11-13 02:01
Thanks for your report and the video demonstrating the issue! - If you have internal development capabilities, pull requests are always welcome, otherwise feel free to get in touch privately with the Catalyst sales team if you would like to investigate commercial support options.

Otherwise this will likely sit here until one of our clients experiences this issue and asks us to look into it further.

thanks!

**Comment by 1991chandanKumar** [comment] 2023-11-13 04:36
Dear sir


Thank you for your reply. How can I get in touch privately with the
Catalyst sales team to investigate commercial support options?

Regards

Chandan kumar

**Comment by danmarsden** [comment] 2023-11-13 05:35
Hi Chandan - I understand you've already been in touch with our sales team and our Customer Success Co-ordinator (Aafreen) has responded to your email - thanks!

**Comment by 1991chandanKumar** [comment] 2023-11-13 07:02
I am not able to find Afreen mail. It would be great if you could kindly
send her email Id

Chandan kumar

**Comment by danmarsden** [comment] 2023-11-13 20:06
check your spam filters - your initial email got flagged as spam on our end too due partly due to the hotmail address you are using - if you have another non free email address (work/university email etc) that you can use - try sending a follow up email to our enquiries email address using that email (referencing this message here in github) again and Aafreen will be back in touch - thanks!

**Comment by alexmorrisnz** [comment] 2023-11-26 21:44
Closing as wont fix, the issue you are having is caused by multiple discussion embeds on the same page. The plugin was only designed for one embed per page.

If you'd like to fund the development work to add support for multiple embeds please get in contact with Aafreen. Thanks

**Closed as not planned by alexmorrisnz** 2023-11-26 21:44 UTC
Labels: bug, wontfix
